config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'cart', to: 'carts#show', format: false
  resources :products
  resources :accounts

  root :to => "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  has_many :friends
  has_many :friend_accounts, through: :friends
  has_one :cart

  validates :name, presence: true, if: :name_exclude_pattern
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 100 }
  validates_length_of :name, minimum: 8
  def name_exclude_pattern
    errors.add(:name, 'invalid format.') unless name !~ /^[0-9]+$/
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :account, optional: true
  has_many :products
end

app/models/friend.rb
# frozen_string_literal: true

class Friend < ApplicationRecord
  belongs_to :account
  belongs_to :friend_account, class_name: 'Account'
  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverses, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_match_options)
  end

  def destroy_inverses
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_match_options)
  end

  def inverses
    self.class.where(inverse_match_options)
  end

  def inverse_match_options
    { friend_account_id: account_id, account_id: friend_account_id }
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :cart, optional: true
  validates :name, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.order('age')
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show; end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit; end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :age)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_current_cart

  def set_current_cart
    session[:cart_id] ||= Cart.create.id
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    cart = Cart.find(session[:cart_id])
    @products = cart.products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  include ProductsHelper
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    products_list_partial_nam
    end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def products_list_partial_nam
    sum = Product.all.count
    result = sum > 0 ? '_list' : '_empty'
    render result.to_s
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/accounts/_form.html.haml
= form_with(model: account, local: true) do |form|
  - if account.errors.any?
    #error_explanation
      %h2
        = pluralize(account.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - account.errors.full_messages.each do |message|
          %li= message
  %form.form-inline
    .form-group
      = form.label :name
      = form.text_field :name, class: "form-control"
    .form-group
      = form.label :age
      = form.number_field :age, class: "form-control"
    .form-group
      = form.submit class: "btn btn-default"

app/views/accounts/edit.html.haml
%h1 Editing Account
= render 'form', account: @account
= link_to 'Show', @account, class: "btn btn-default"
|
= link_to 'Back', accounts_path, class: "btn btn-default"

app/views/accounts/index.html.haml
%p#notice= notice
%h1 Accounts
%table.table
  %thead
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Age
  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.name
        %td= account.age
        %td= link_to 'Show', account, class: "btn btn-primary"
        %td= link_to 'Edit', edit_account_path(account), class: "btn btn-success"
        %td= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
%br/
= link_to 'New Account', new_account_path, class: "btn btn-primary"

app/views/accounts/new.html.haml
%h1 New Account
= render 'form', account: @account
= link_to 'Back', accounts_path, class: "btn btn-default"

app/views/accounts/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @account.name
%p
  %strong Age:
  = @account.age
= link_to 'Edit', edit_account_path(@account), class: "btn btn-default"
|
= link_to 'Back', accounts_path, class: "btn btn-default"

app/views/carts/show.html.haml
%p#notice= notice
%h1 Carts
%table.table
  %thead
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Description
      %th{:scope => "col"} Price
      %th{:scope => "col"} Account_id
  %tbody
    - @products.each do |product|
      %tr
        %td= product.name
        %td= product.description
        %td= product.price
        %td= product.cart_id
%br/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsMonastyrskyi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
        %ul.nav.navbar-nav
          %li= link_to 'Accountsss', accounts_path
          %li= link_to 'Products', root_path
          %li= link_to 'Cart', cart_path
  %body
    .container
      = yield

app/views/products/_empty.html.haml
%h1 Sorry there are no any products
= link_to 'Add product', new_product_path, class: "btn btn-primary"

app/views/products/_form.html.haml
= form_with(model: product, local: true) do |form|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message
  %form.form-inline
    .form-group
      = form.label :name
      = form.text_field :name, class: "form-control"
    .form-group
      = form.label :description
      = form.text_field :description, class: "form-control"
    .form-group
      = form.label :price
      = form.number_field :price, class: "form-control"
    .form-group
      = form.submit class: "btn btn-default"

app/views/products/_list.html.haml
.site-wrap
  %p#notice= notice
  %h1 Products
  %table.table
    %thead
      %tr
        %th{:scope => "col"} Name
        %th{:scope => "col"} Description
        %th{:scope => "col"} Price
    %tbody
      - @products.each do |product|
        %thead
          %tr
            %td= product.name
            %td= product.description
            %td= product.price
            %td= link_to 'Show', product, class: "btn btn-primary"
            %td= link_to 'Edit', edit_product_path(product), class: "btn btn-success"
            %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
  %br/
  = link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/edit.html.haml
%h1 Editing Product
= render 'form', product: @product
= link_to 'Show', @product, class: "btn btn-default"
|
= link_to 'Back', products_path, class: "btn btn-default"

app/views/products/new.html.haml
%h1 New Product
= render 'form', product: @product
= link_to 'Back', products_path, class: "btn btn-default"

app/views/products/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @product.name
%p
  %strong Description:
  = @product.description
%p
  %strong Price:
  = @product.price
= link_to 'Edit', edit_product_path(@product), class: "btn btn-default"
|
\#{link_to 'Back', products_path, class: "btn btn-default"}

app/views/welcome/index.html.haml
%h1 Welcome to my first app
%p Created by Yurii Monastyrskyi
= link_to 'Accounts', accounts_path